### PR TITLE
set password via webrepl_cli on first connect

### PR DESCRIPTION
**Pull request by lumbric**
Makes the login a bit more robust: just waiting for ":" in "Password:" may have surprising results if it is actually the setup password dialog and it tells us "Confirm password:" after setting it the first time. This simply sends the password a second time, i.e. sets the password first and then logs in.

### CODE REVIEW

**Comment by pfalcon** [comment]
Thanks, but we don't want automation of such level. Actually we want "automation" (in different context would be called "wide attack surface") of this matter to be not possible at all: http://forum.micropython.org/viewtopic.php?f=16&t=2492.

**Comment by lumbric** [comment]
Thanks for the link! I agree totally with with the plans described there. In fact I was wondering if this shouldn't be changed to a more secure way of setting and storing the password. The only reason I wrote the pull request: in the current version webrepl_cli hangs completely if you do not set the password before, because it reads only ':' instead of checking the complete response (which could be either 'Password:' or 'New password:' or 'Confirm password:'.

**Comment by pfalcon** [comment]
Thanks for understanding. Generally, it's good idea before developing a substantial patch to notify about your plans, to have a chance to discuss the best approach to it.

**Comment by lumbric** [comment]
It was more of a fast 2 hour implementation after a ESP8266 in our local
hackerspace, so there was not much room for plans before... ;-)  But
don't worry, I was aware that the patch might not make sense, but it was
the easiest way to let the patch explain the plan.

**Pull request closed without merging**
